<html lang="en">
<body>
    Nombre: {{$nombre}} <br>
    Carnet de identidad: {{$ci}} <br>
    Celular: {{$celular}}<br>
    Correo: {{$correo}}<br>
    Mensaje: {{$mensaje}}<br>    
    <!--<div style="border-style:solid;border-width:thin;border-color:#dadce0;border-radius:8px;padding:40px 20px" align="center" class="m_-2175175213603781935mdv2rw"><img src="https://ci3.googleusercontent.com/meips/ADKq_NZa00tQPIx4fdFGtuHSHzYQ-whZFD7HWD3OhXR05fT4XqJ_Wca2erL9R9_382bPBUom-sDOVfi4G3FXbYaZsHsGqQUAL6-JIKgEzWlarZbeNSLveyc6EKOURFQhphfzG2ZAwLiyrJsC=s0-d-e1-ft#https://www.gstatic.com/images/branding/googlelogo/2x/googlelogo_color_74x24dp.png" width="74" height="24" aria-hidden="true" style="margin-bottom:16px" alt="Google" class="CToWUd" data-bit="iit"><div style="font-family:'Google Sans',Roboto,RobotoDraft,Helvetica,Arial,sans-serif;border-bottom:thin solid #dadce0;color:rgba(0,0,0,0.87);line-height:32px;padding-bottom:24px;text-align:center;word-break:break-word"><div style="font-size:24px">2-Step Verification turned on </div><table align="center" style="margin-top:8px"><tbody><tr style="line-height:normal"><td align="right" style="padding-right:8px"><img width="20" height="20" style="width:20px;height:20px;vertical-align:sub;border-radius:50%" src="https://lh3.googleusercontent.com/a/ACg8ocLjdqtTaaRsXDm2yOEDs20j_xMT8LNuvyX1EEjXlY14=s96-c" alt="" class="CToWUd" data-bit="iit"></td><td><a style="font-family:'Google Sans',Roboto,RobotoDraft,Helvetica,Arial,sans-serif;color:rgba(0,0,0,0.87);font-size:14px;line-height:20px">udemy77412318@gmail.com</a></td></tr></tbody></table> </div><div style="font-family:Roboto-Regular,Helvetica,Arial,sans-serif;font-size:14px;color:rgba(0,0,0,0.87);line-height:20px;padding-top:20px;text-align:left"><p>Your Google Account <a href="mailto:udemy77412318@gmail.com" target="_blank">udemy77412318@gmail.com</a> is now protected with 2-Step Verification. When you sign in on a new or untrusted device, you’ll need your second factor to verify your identity.</p><p><b>Don't get locked out!</b><br>You can add a backup phone or get backup codes to use when you don’t have your second factor with you.</p>You can <a href="https://accounts.google.com/AccountChooser?Email=udemy77412318@gmail.com&amp;continue=https://myaccount.google.com/signinoptions/two-step-verification?rfn%3D16%26rfnc%3D1%26eid%3D-5357374991877819538%26et%3D0" style="text-decoration:none;color:#4285f4" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://accounts.google.com/AccountChooser?Email%3Dudemy77412318@gmail.com%26continue%3Dhttps://myaccount.google.com/signinoptions/two-step-verification?rfn%253D16%2526rfnc%253D1%2526eid%253D-5357374991877819538%2526et%253D0&amp;source=gmail&amp;ust=1708458762094000&amp;usg=AOvVaw0OPazeivEX1goLat_bxP99">review your 2SV settings</a>  to make changes.</div><div style="padding-top:20px;font-size:12px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:center">You can also see security activity at<br><a style="color:rgba(0,0,0,0.87);text-decoration:inherit">https://myaccount.google.com/<wbr>notifications</a></div></div>-->
</body>
</html>